### ISSUE TITLE
slash command is not converting the letter 'z'

### ISSUE THREAD

**Issue by bigjonroberts** [bigjonroberts/scrabblinator#2]
There are tests now that actually detect this bug.
They can be run via either of the following commands:
`dotnet test ScrabblinatorTests/ScrabblinatorTests.fsproj`
`docker build -t scrabblinator .`

**Comment by spencerwi** [comment]
I have a PR to fix this, though it's a pretty trivial fix: lowercase 'z' is ASCII char 122; the range before only included through 121.
