### ISSUE TITLE
what does this project do?

### ISSUE THREAD

**Issue by jrr** [bigjonroberts/scrabblinator#4]
The project's name caught my eye in a Hacktoberfest issue search, but I can't tell from the Readme what it does.

Skimming through the source, it looks like it maybe adds a slash command to convert a string of chars into a series of slackmojis that you need to have already installed?

**Comment by WritingPanda** [comment]
It allows a user in a slack group to do `/scrabble message` and get an output of the message using emojis within the slack group. It expects that you have scrabble emojis named :scrabble-a: all the way to :scrabble-z:.

**Comment by bigjonroberts** [comment]
I'll add documentation on how to easily upload the emoji's
